### ISSUE TITLE
help regarding vars

### ISSUE THREAD

**Issue by ramanveerji** [FayasNoushad/YouTube-Downloader#5]
I tried adding
DEF_THUMB_NAIL_VID_S <telegraph image_link> 
DEF_WATER_MARK_FILE <telegraph image_link> 
UPDATE_CHANNEL <channel username without @>
SCREENSHOTS False (Still bot is sending screenshots)
but these are not working, can you see and tell me if i am doing something wrong here?

**Comment by FayasNoushad** [comment]
Update channel is working. Screenshot support removing soon other will fix soon. If you like me please follow me 😉.
